version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd muscle_app && yarn start"
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true